variables:
  IMAGE_TAG: dreg.harmonic.co.nz:5000/harmonic/geonz:$CI_PIPELINE_ID
  PACKAGE_DIR: '/geonz'

stages:
  - build
  - testing

build-docker-container:
  stage: build
  tags:
      - shell
      - dockerbuild
      - wellington
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

tests-and-coverage:
  stage: testing
  tags:
      - docker
  image: $IMAGE_TAG
  variables:
    GIT_STRATEGY: none
    KUBERNETES_MEMORY_REQUEST: 6Gi
  script:
    - cd $PACKAGE_DIR
    - R -e 'devtools::test()'
    - R -e 'covr::package_coverage(type = c("tests", "examples"), quiet = FALSE)'

package-check:
  stage: testing
  tags:
      - docker
  image: $IMAGE_TAG
  variables:
    GIT_STRATEGY: none
    KUBERNETES_MEMORY_REQUEST: 6Gi
  script:
    - cd $PACKAGE_DIR
    - R -e 'devtools::check()'
